id     = "PROOF"
name   = "Proof"
header = "options/proof_options.h"

[[option]]
  name       = "lfscLetification"
  category   = "regular"
  long       = "lfsc-letification"
  type       = "bool"
  default    = "true"
  read_only  = true
  help       = "turns on global letification in LFSC proofs"

[[option]]
  name       = "aggressiveCoreMin"
  category   = "regular"
  long       = "aggressive-core-min"
  type       = "bool"
  default    = "false"
  read_only  = true
  help       = "turns on aggressive unsat core minimization (experimental)"

[[option]]
  name       = "fewerPreprocessingHoles"
  category   = "regular"
  long       = "fewer-preprocessing-holes"
  type       = "bool"
  default    = "false"
  help       = "try to eliminate preprocessing holes in proofs"

[[option]]
  name       = "allowEmptyDependencies"
  category   = "regular"
  long       = "allow-empty-dependencies"
  type       = "bool"
  default    = "false"
  read_only  = true
  help       = "if unable to track the dependencies of a rewritten/preprocessed assertion, fail silently"

[[option]]
  name       = "lazyProofs"
  category   = "regular"
  long       = "lazy-proofs"
  type       = "bool"
  default    = "true"
  read_only  = true
  help       = "Use lazy proofs (UF, AX)"

[[option]]
  name       = "newProofs"
  category   = "regular"
  long       = "new-proofs"
  type       = "bool"
  default    = "false"
  read_only  = true
  help       = "Use new proof module"

[[option]]
  name       = "proofFormat"
  category   = "regular"
  long       = "proof-format=MODE"
  type       = "ProofFormatMode"
  default    = "VERIT"
  help       = "mode for proof format"
  help_mode  = "Modes for proof formats."
[[option.mode.VERIT]]
  name = "verit"
  help = "Use veriT's proof format."
[[option.mode.LEAN]]
  name = "lean"
  help = "Use Lean's proof format."
[[option.mode.LFSC]]
  name = "lfsc"
  help = "Use LFSC's proof format (UNSUPPORTED)."
